/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as HubsRouteImport } from './routes/hubs'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CatalogueProductIdRouteImport } from './routes/catalogue.$productId'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppProducerRouteImport } from './routes/app.producer'
import { Route as AppPlansRouteImport } from './routes/app.plans'
import { Route as AppOrdersReceivedRouteImport } from './routes/app.orders-received'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppGestionRouteImport } from './routes/app.gestion'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as CheckoutPayOrderIdRouteImport } from './routes/checkout.pay.$orderId'
import { Route as AppProductsNewRouteImport } from './routes/app.products.new'
import { Route as AppProductsProductIdRouteImport } from './routes/app.products.$productId'
import { Route as AppOrdersOrderIdRouteImport } from './routes/app.orders.$orderId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminProducersRouteImport } from './routes/app.admin.producers'
import { Route as AppAdminHubsRouteImport } from './routes/app.admin.hubs'
import { Route as ApiPublicStuartWebhookRouteImport } from './routes/api/public/stuart-webhook'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsRoute = HubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const CatalogueProductIdRoute = CatalogueProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogueRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProducerRoute = AppProducerRouteImport.update({
  id: '/producer',
  path: '/producer',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersReceivedRoute = AppOrdersReceivedRouteImport.update({
  id: '/orders-received',
  path: '/orders-received',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppGestionRoute = AppGestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const CheckoutPayOrderIdRoute = CheckoutPayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => CheckoutRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProducersRoute = AppAdminProducersRouteImport.update({
  id: '/producers',
  path: '/producers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHubsRoute = AppAdminHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicStuartWebhookRoute = ApiPublicStuartWebhookRouteImport.update({
  id: '/api/public/stuart-webhook',
  path: '/api/public/stuart-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/hubs': typeof HubsRoute
  '/panier': typeof PanierRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/gestion': typeof AppGestionRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/orders-received': typeof AppOrdersReceivedRoute
  '/app/plans': typeof AppPlansRoute
  '/app/producer': typeof AppProducerRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/catalogue/$productId': typeof CatalogueProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/public/stuart-webhook': typeof ApiPublicStuartWebhookRoute
  '/app/admin/hubs': typeof AppAdminHubsRoute
  '/app/admin/producers': typeof AppAdminProducersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/checkout/pay/$orderId': typeof CheckoutPayOrderIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/hubs': typeof HubsRoute
  '/panier': typeof PanierRoute
  '/app/gestion': typeof AppGestionRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/orders-received': typeof AppOrdersReceivedRoute
  '/app/plans': typeof AppPlansRoute
  '/app/producer': typeof AppProducerRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/catalogue/$productId': typeof CatalogueProductIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/api/public/stuart-webhook': typeof ApiPublicStuartWebhookRoute
  '/app/admin/hubs': typeof AppAdminHubsRoute
  '/app/admin/producers': typeof AppAdminProducersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/checkout/pay/$orderId': typeof CheckoutPayOrderIdRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/hubs': typeof HubsRoute
  '/panier': typeof PanierRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/gestion': typeof AppGestionRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/orders-received': typeof AppOrdersReceivedRoute
  '/app/plans': typeof AppPlansRoute
  '/app/producer': typeof AppProducerRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/catalogue/$productId': typeof CatalogueProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/api/public/stuart-webhook': typeof ApiPublicStuartWebhookRoute
  '/app/admin/hubs': typeof AppAdminHubsRoute
  '/app/admin/producers': typeof AppAdminProducersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/app/products/$productId': typeof AppProductsProductIdRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/checkout/pay/$orderId': typeof CheckoutPayOrderIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/catalogue'
    | '/checkout'
    | '/hubs'
    | '/panier'
    | '/app/admin'
    | '/app/gestion'
    | '/app/orders'
    | '/app/orders-received'
    | '/app/plans'
    | '/app/producer'
    | '/app/products'
    | '/app/subscriptions'
    | '/catalogue/$productId'
    | '/checkout/'
    | '/api/public/stuart-webhook'
    | '/app/admin/hubs'
    | '/app/admin/producers'
    | '/app/admin/users'
    | '/app/orders/$orderId'
    | '/app/products/$productId'
    | '/app/products/new'
    | '/checkout/pay/$orderId'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/catalogue'
    | '/hubs'
    | '/panier'
    | '/app/gestion'
    | '/app/orders'
    | '/app/orders-received'
    | '/app/plans'
    | '/app/producer'
    | '/app/products'
    | '/app/subscriptions'
    | '/catalogue/$productId'
    | '/checkout'
    | '/api/public/stuart-webhook'
    | '/app/admin/hubs'
    | '/app/admin/producers'
    | '/app/admin/users'
    | '/app/orders/$orderId'
    | '/app/products/$productId'
    | '/app/products/new'
    | '/checkout/pay/$orderId'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/catalogue'
    | '/checkout'
    | '/hubs'
    | '/panier'
    | '/app/admin'
    | '/app/gestion'
    | '/app/orders'
    | '/app/orders-received'
    | '/app/plans'
    | '/app/producer'
    | '/app/products'
    | '/app/subscriptions'
    | '/catalogue/$productId'
    | '/checkout/'
    | '/api/public/stuart-webhook'
    | '/app/admin/hubs'
    | '/app/admin/producers'
    | '/app/admin/users'
    | '/app/orders/$orderId'
    | '/app/products/$productId'
    | '/app/products/new'
    | '/checkout/pay/$orderId'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CatalogueRoute: typeof CatalogueRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  HubsRoute: typeof HubsRoute
  PanierRoute: typeof PanierRoute
  ApiPublicStuartWebhookRoute: typeof ApiPublicStuartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs': {
      id: '/hubs'
      path: '/hubs'
      fullPath: '/hubs'
      preLoaderRoute: typeof HubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/catalogue/$productId': {
      id: '/catalogue/$productId'
      path: '/$productId'
      fullPath: '/catalogue/$productId'
      preLoaderRoute: typeof CatalogueProductIdRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/producer': {
      id: '/app/producer'
      path: '/producer'
      fullPath: '/app/producer'
      preLoaderRoute: typeof AppProducerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders-received': {
      id: '/app/orders-received'
      path: '/orders-received'
      fullPath: '/app/orders-received'
      preLoaderRoute: typeof AppOrdersReceivedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gestion': {
      id: '/app/gestion'
      path: '/gestion'
      fullPath: '/app/gestion'
      preLoaderRoute: typeof AppGestionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/checkout/pay/$orderId': {
      id: '/checkout/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/checkout/pay/$orderId'
      preLoaderRoute: typeof CheckoutPayOrderIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/app/products/new': {
      id: '/app/products/new'
      path: '/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/products/$productId': {
      id: '/app/products/$productId'
      path: '/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/orders/$orderId': {
      id: '/app/orders/$orderId'
      path: '/$orderId'
      fullPath: '/app/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/producers': {
      id: '/app/admin/producers'
      path: '/producers'
      fullPath: '/app/admin/producers'
      preLoaderRoute: typeof AppAdminProducersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/hubs': {
      id: '/app/admin/hubs'
      path: '/hubs'
      fullPath: '/app/admin/hubs'
      preLoaderRoute: typeof AppAdminHubsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/stuart-webhook': {
      id: '/api/public/stuart-webhook'
      path: '/api/public/stuart-webhook'
      fullPath: '/api/public/stuart-webhook'
      preLoaderRoute: typeof ApiPublicStuartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminHubsRoute: typeof AppAdminHubsRoute
  AppAdminProducersRoute: typeof AppAdminProducersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminHubsRoute: AppAdminHubsRoute,
  AppAdminProducersRoute: AppAdminProducersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppGestionRoute: typeof AppGestionRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppOrdersReceivedRoute: typeof AppOrdersReceivedRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProducerRoute: typeof AppProducerRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppGestionRoute: AppGestionRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppOrdersReceivedRoute: AppOrdersReceivedRoute,
  AppPlansRoute: AppPlansRoute,
  AppProducerRoute: AppProducerRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CatalogueRouteChildren {
  CatalogueProductIdRoute: typeof CatalogueProductIdRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueProductIdRoute: CatalogueProductIdRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutPayOrderIdRoute: typeof CheckoutPayOrderIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutPayOrderIdRoute: CheckoutPayOrderIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CatalogueRoute: CatalogueRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  HubsRoute: HubsRoute,
  PanierRoute: PanierRoute,
  ApiPublicStuartWebhookRoute: ApiPublicStuartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
